In [114]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [115]:
df_train=pd.read_csv("trainClassification.csv")
df_test=pd.read_csv("testClassification.csv")

In [116]:
train=df_train.drop(['RUL','label'],axis=1)
test=df_test.drop(['RUL','label'],axis=1)
df=train

In [117]:
train.shape

(20631, 27)

In [118]:
train.describe()

vehicleId          days       ecoMode      cityMode  sportMode  \
count  20631.000000  20631.000000  20631.000000  20631.000000    20631.0   
mean      51.506568    108.807862     -0.000009      0.000002      100.0   
std       29.227633     68.880990      0.002187      0.000293        0.0   
min        1.000000      1.000000     -0.008700     -0.000600      100.0   
25%       26.000000     52.000000     -0.001500     -0.000200      100.0   
50%       52.000000    104.000000      0.000000      0.000000      100.0   
75%       77.000000    156.000000      0.001500      0.000300      100.0   
max      100.000000    362.000000      0.008700      0.000600      100.0   

                 s1            s2            s3            s4            s5  \
count  2.063100e+04  20631.000000  20631.000000  20631.000000  2.063100e+04   
mean   5.186700e+02    642.680934   1590.523119   1408.933782  1.462000e+01   
std    6.537152e-11      0.500053      6.131150      9.000605  3.394700e-12   
min    5.186700e+02    641.210000   1571.040000   1382.250000  1.462000e+01   
25%    5.186700e+02    642.325000   1586.260000   1402.360000  1.462000e+01   
50%    5.186700e+02    642.640000   1590.100000   1408.040000  1.462000e+01   
75%    5.186700e+02    643.000000   1594.380000   1414.555000  1.462000e+01   
max    5.186700e+02    644.530000   1616.910000   1441.490000  1.462000e+01   

       ...           s13           s14           s15           s16  \
count  ...  20631.000000  20631.000000  20631.000000  2.063100e+04   
mean   ...   2388.096152   8143.752722      8.442146  3.000000e-02   
std    ...      0.071919     19.076176      0.037505  1.556432e-14   
min    ...   2387.880000   8099.940000      8.324900  3.000000e-02   
25%    ...   2388.040000   8133.245000      8.414900  3.000000e-02   
50%    ...   2388.090000   8140.540000      8.438900  3.000000e-02   
75%    ...   2388.140000   8148.310000      8.465600  3.000000e-02   
max    ...   2388.560000   8293.720000      8.584800  3.000000e-02   

                s17      s18      s19           s20           s21  \
count  20631.000000  20631.0  20631.0  20631.000000  20631.000000   
mean     393.210654   2388.0    100.0     38.816271     23.289705   
std        1.548763      0.0      0.0      0.180746      0.108251   
min      388.000000   2388.0    100.0     38.140000     22.894200   
25%      392.000000   2388.0    100.0     38.700000     23.221800   
50%      393.000000   2388.0    100.0     38.830000     23.297900   
75%      394.000000   2388.0    100.0     38.950000     23.366800   
max      400.000000   2388.0    100.0     39.430000     23.618400   

           label_bc  
count  20631.000000  
mean       0.150259  
std        0.357334  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        0.000000  
max        1.000000  

[8 rows x 27 columns]

In [119]:
train['label_bc'].describe()

count    20631.000000
mean         0.150259
std          0.357334
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: label_bc, dtype: float64

#### only 15% positive(1) and 85% negative(0) , so it is unbalaced dataset

In [120]:
df_train[df_train['RUL']==0].days.describe()

count    100.000000
mean     206.310000
std       46.342749
min      128.000000
25%      177.000000
50%      199.000000
75%      229.250000
max      362.000000
Name: days, dtype: float64

In [121]:
df

vehicleId  days  ecoMode  cityMode  sportMode      s1      s2       s3  \
0              1     1  -0.0007   -0.0004        100  518.67  641.82  1589.70   
1              1     2   0.0019   -0.0003        100  518.67  642.15  1591.82   
2              1     3  -0.0043    0.0003        100  518.67  642.35  1587.99   
3              1     4   0.0007    0.0000        100  518.67  642.35  1582.79   
4              1     5  -0.0019   -0.0002        100  518.67  642.37  1582.85   
...          ...   ...      ...       ...        ...     ...     ...      ...   
20626        100   196  -0.0004   -0.0003        100  518.67  643.49  1597.98   
20627        100   197  -0.0016   -0.0005        100  518.67  643.54  1604.50   
20628        100   198   0.0004    0.0000        100  518.67  643.42  1602.46   
20629        100   199  -0.0011    0.0003        100  518.67  643.23  1605.26   
20630        100   200  -0.0032   -0.0005        100  518.67  643.85  1600.38   

            s4     s5  ...      s13      s14     s15   s16  s17   s18  s19  \
0      1400.60  14.62  ...  2388.02  8138.62  8.4195  0.03  392  2388  100   
1      1403.14  14.62  ...  2388.07  8131.49  8.4318  0.03  392  2388  100   
2      1404.20  14.62  ...  2388.03  8133.23  8.4178  0.03  390  2388  100   
3      1401.87  14.62  ...  2388.08  8133.83  8.3682  0.03  392  2388  100   
4      1406.22  14.62  ...  2388.04  8133.80  8.4294  0.03  393  2388  100   
...        ...    ...  ...      ...      ...     ...   ...  ...   ...  ...   
20626  1428.63  14.62  ...  2388.26  8137.60  8.4956  0.03  397  2388  100   
20627  1433.58  14.62  ...  2388.22  8136.50  8.5139  0.03  395  2388  100   
20628  1428.18  14.62  ...  2388.24  8141.05  8.5646  0.03  398  2388  100   
20629  1426.53  14.62  ...  2388.23  8139.29  8.5389  0.03  395  2388  100   
20630  1432.14  14.62  ...  2388.26  8137.33  8.5036  0.03  396  2388  100   

         s20      s21  label_bc  
0      39.06  23.4190         0  
1      39.00  23.4236         0  
2      38.95  23.3442         0  
3      38.88  23.3739         0  
4      38.90  23.4044         0  
...      ...      ...       ...  
20626  38.49  22.9735         1  
20627  38.30  23.1594         1  
20628  38.44  22.9333         1  
20629  38.29  23.0640         1  
20630  38.37  23.0522         1  

[20631 rows x 27 columns]

In [122]:
df['label_bc'].value_counts()[1]

3100

In [123]:
df['label_bc'].count()

20631

In [124]:
print(df['label_bc'].value_counts())
print('\nNegaitve samples =  {0:.0%}'.format(df['label_bc'].value_counts()[1]/df['label_bc'].count()))
print('\nPosiitve samples =  {0:.0%}'.format(df['label_bc'].value_counts()[0]/df['label_bc'].count()))

0    17531
1     3100
Name: label_bc, dtype: int64

Negaitve samples =  15%

Posiitve samples =  85%


In [125]:
df['label_bc'].value_counts()[1]/df['label_bc'].count()

0.15025931850128446

In [126]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [127]:
co_relation=train.corr()["label_bc"]
co_relation

vehicleId   -1.448230e-02
days         5.036790e-01
ecoMode      1.049943e-02
cityMode     9.402176e-03
sportMode             NaN
s1           8.198058e-16
s2           5.814040e-01
s3           5.618920e-01
s4           6.484064e-01
s5           2.220435e-15
s6           5.957942e-02
s7          -6.255919e-01
s8           5.429101e-01
s9           4.195389e-01
s10         -5.044491e-16
s11          6.656552e-01
s12         -6.401737e-01
s13          5.399146e-01
s14          3.410628e-01
s15          6.187318e-01
s16         -3.382962e-16
s17          5.830666e-01
s18                   NaN
s19                   NaN
s20         -5.999121e-01
s21         -6.064804e-01
label_bc     1.000000e+00
Name: label_bc, dtype: float64

In [128]:
co_relation.abs().sort_values(ascending=False)

label_bc     1.000000e+00
s11          6.656552e-01
s4           6.484064e-01
s12          6.401737e-01
s7           6.255919e-01
s15          6.187318e-01
s21          6.064804e-01
s20          5.999121e-01
s17          5.830666e-01
s2           5.814040e-01
s3           5.618920e-01
s8           5.429101e-01
s13          5.399146e-01
days         5.036790e-01
s9           4.195389e-01
s14          3.410628e-01
s6           5.957942e-02
vehicleId    1.448230e-02
ecoMode      1.049943e-02
cityMode     9.402176e-03
s5           2.220435e-15
s1           8.198058e-16
s10          5.044491e-16
s16          3.382962e-16
sportMode             NaN
s18                   NaN
s19                   NaN
Name: label_bc, dtype: float64

In [129]:
corelated=co_relation.abs().sort_values(ascending=False)[1:].head(14).index
corelated

Index(['s11', 's4', 's12', 's7', 's15', 's21', 's20', 's17', 's2', 's3', 's8',
       's13', 'days', 's9'],
      dtype='object')

In [130]:
not_corelated=co_relation.abs().sort_values(ascending=False)[15:].index
not_corelated

Index(['s14', 's6', 'vehicleId', 'ecoMode', 'cityMode', 's5', 's1', 's10',
       's16', 'sportMode', 's18', 's19'],
      dtype='object')

In [131]:
X_train,y_train=train.drop('label_bc',axis=1),train["label_bc"]

In [132]:
X_test,y_test=test.drop('label_bc',axis=1),test["label_bc"]

### Feature selection
- using  SelectFromModel(Lasso(alpha=0.005, random_state=0))

In [133]:
from sklearn.linear_model import Lasso
from sklearn.feature_selection import SelectFromModel

In [134]:
# select a suitable alpha (equivalent of penalty).
# The bigger the alpha the less features that will be selected.
# 0.005 due his indrustry expericence

feature_sel_model = SelectFromModel(Lasso(alpha=0.005, random_state=0)) # remember to set the seed, the random state in this function
feature_sel_model.fit(X_train,y_train)

SelectFromModel(estimator=Lasso(alpha=0.005, random_state=0))

In [135]:
feature_sel_model.get_support()

array([ True,  True, False, False, False, False,  True,  True,  True,
       False, False,  True, False,  True, False, False,  True, False,
        True, False, False,  True, False, False, False, False])

In [136]:
cols=X_train.columns

In [137]:
# let's print the number of total and selected features

# this is how we can make a list of the selected features
selected_feat = cols[(feature_sel_model.get_support())]
selected_feat

Index(['vehicleId', 'days', 's2', 's3', 's4', 's7', 's9', 's12', 's14', 's17'], dtype='object')

In [138]:
print(corelated)
corelated.difference(selected_feat)

Index(['s11', 's4', 's12', 's7', 's15', 's21', 's20', 's17', 's2', 's3', 's8',
       's13', 'days', 's9'],
      dtype='object')


Index(['s11', 's13', 's15', 's20', 's21', 's8'], dtype='object')

In [139]:
import scipy.stats as stat
import pylab
import matplotlib.pyplot as plt
def plot_data(df,feature):
    print(feature)
    plt.figure(figsize=(10,6))
    plt.subplot(1,2,1)
    df[feature].hist()
    plt.subplot(1,2,2)
    stat.probplot(df[feature],dist='norm',plot=pylab)
    plt.show()

In [140]:
import numpy as np
def distributions(df,feature):
    df[feature+'_log']=np.log(df[feature])
    plot_data(df,feature+'_log')
    df[feature+'_log1p']=np.log1p(df[feature])
    plot_data(df,feature+'_log1p')
    df[feature+'_reciprocal']=1/df[feature]
    plot_data(df,feature+'_reciprocal')
    df[feature+'_sqaure']=df[feature]**(1/2)
    plot_data(df,feature+'_sqaure')
    df[feature+'exponential']=df[feature]**(1/1.2)
    plot_data(df,feature+'exponential')
    df[feature+'_boxcox'],parameters=stat.boxcox(train[feature])
    print(parameters)
    plot_data(df,feature+'_boxcox')

In [141]:
from sklearn.linear_model import LogisticRegression
logreg=LogisticRegression()
logreg.fit(X_train,y_train)

C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [142]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
y_pred=logreg.predict(X_test)
train_pred=logreg.predict(X_train)
def metrices(pred,y_test):
    print("accuracy_score {}".format(accuracy_score(pred,y_test)))
    print("\nconfusion_matrix \n{}".format(confusion_matrix(pred,y_test)))
    print("\nclassification_report {}".format(classification_report(pred,y_test)))

metrices(y_pred,y_test)


accuracy_score 0.89

confusion_matrix 
[[74 10]
 [ 1 15]]

classification_report               precision    recall  f1-score   support

           0       0.99      0.88      0.93        84
           1       0.60      0.94      0.73        16

    accuracy                           0.89       100
   macro avg       0.79      0.91      0.83       100
weighted avg       0.92      0.89      0.90       100



### rough work

In [143]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.99      0.88      0.93        84
           1       0.60      0.94      0.73        16

    accuracy                           0.89       100
   macro avg       0.79      0.91      0.83       100
weighted avg       0.92      0.89      0.90       100



In [144]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.88      0.99      0.93        75
           1       0.94      0.60      0.73        25

    accuracy                           0.89       100
   macro avg       0.91      0.79      0.83       100
weighted avg       0.90      0.89      0.88       100



In [145]:
confusion_matrix(y_pred,y_test)

array([[74, 10],
       [ 1, 15]], dtype=int64)

In [146]:
confusion_matrix(y_test,y_pred)

array([[74,  1],
       [10, 15]], dtype=int64)

In [147]:
test['label_bc'].value_counts()

0    75
1    25
Name: label_bc, dtype: int64

In [148]:
metrices(train_pred,y_train)

accuracy_score 0.94154427802821

confusion_matrix 
[[17050   725]
 [  481  2375]]

classification_report               precision    recall  f1-score   support

           0       0.97      0.96      0.97     17775
           1       0.77      0.83      0.80      2856

    accuracy                           0.94     20631
   macro avg       0.87      0.90      0.88     20631
weighted avg       0.94      0.94      0.94     20631



### cross validation for logistic 

In [149]:
from sklearn.model_selection import cross_val_score
score=cross_val_score(logreg,X_train,y_train,cv=10)

C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 

In [150]:
score

array([0.95445736, 0.95104217, 0.93504605, 0.94716432, 0.95007271,
       0.94716432, 0.92825982, 0.94328648, 0.94377121, 0.92971401])

In [151]:
score.mean()

0.9429978450138468

In [152]:
#fit naive bayes
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVR

In [153]:
### classifier models
models = []
models.append(('LogisticRegression', LogisticRegression()))
models.append(('Naive Bayes',GaussianNB()))
models.append(('RandomForest', RandomForestClassifier()))
models.append(('Decision Tree', DecisionTreeClassifier()))
models.append(('KNN', KNeighborsClassifier(n_neighbors = 5)))


In [154]:
models

[('LogisticRegression', LogisticRegression()),
 ('Naive Bayes', GaussianNB()),
 ('RandomForest', RandomForestClassifier()),
 ('Decision Tree', DecisionTreeClassifier()),
 ('KNN', KNeighborsClassifier())]

In [155]:
l=[models[i][0] for i in range(len(models))]
l

['LogisticRegression', 'Naive Bayes', 'RandomForest', 'Decision Tree', 'KNN']

In [156]:
dict1={"Classifier":[models[i][0] for i in range(len(models))]}
result_df=pd.DataFrame(dict1)
result_df

Classifier
0  LogisticRegression
1         Naive Bayes
2        RandomForest
3       Decision Tree
4                 KNN

In [157]:
result_df

Classifier
0  LogisticRegression
1         Naive Bayes
2        RandomForest
3       Decision Tree
4                 KNN

## direct

In [158]:
X_train.shape

(20631, 26)

In [159]:
def models_fitting(X_train,X_test,title):
    accuracy=[]
    score=[]
    auc=[]
    for name, model in models:
        print(name)
        model.fit(X_train, y_train)

        # Make predictions.
        predictions = model.predict(X_test)


        #getting training accuracy

        if name!='KNN':
            from sklearn.metrics import accuracy_score
            train_pred = model.predict(X_train)
            print("training accuracy")
            print(accuracy_score(train_pred,y_train))

        # ROC AUC
        from sklearn.metrics import roc_auc_score
        print("roc_auc_score \n{}" .format(roc_auc_score(predictions, y_test)))
        
        # Compute the error.
        from sklearn.metrics import f1_score
        from sklearn.metrics import confusion_matrix
        from sklearn.metrics import accuracy_score
        print("\n f1_score \n",f1_score(predictions, y_test))
        print("\n",confusion_matrix(predictions, y_test))
        print("\n accuracy_score \n",accuracy_score(predictions,y_test))
        
        #ccollecting accuracy,f1_score,roc_auc_score
        
        accuracy.append(accuracy_score(predictions,y_test))
        score.append(f1_score(predictions,y_test))
        auc.append(roc_auc_score(predictions,y_test))
        print('\n')
        print('\n')
    result_df[title+"_A"]=accuracy
    result_df[title+"_f1"]=score
    result_df[title+"_AUC"]=auc

In [160]:
models_fitting(X_train,X_test,'direct')

LogisticRegression


C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


training accuracy
0.94154427802821
roc_auc_score 
0.9092261904761905

 f1_score 
 0.7317073170731707

 [[74 10]
 [ 1 15]]

 accuracy_score 
 0.89




Naive Bayes
training accuracy
0.9292327080606854
roc_auc_score 
0.8968253968253967

 f1_score 
 0.8679245283018867

 [[70  2]
 [ 5 23]]

 accuracy_score 
 0.93




RandomForest
training accuracy
1.0
roc_auc_score 
0.90625

 f1_score 
 0.7999999999999999

 [[73  7]
 [ 2 18]]

 accuracy_score 
 0.91




Decision Tree
training accuracy
1.0
roc_auc_score 
0.8933566433566434

 f1_score 
 0.8085106382978724

 [[72  6]
 [ 3 19]]

 accuracy_score 
 0.91




KNN
roc_auc_score 
0.8235294117647058

 f1_score 
 0.6

 [[72 13]
 [ 3 12]]

 accuracy_score 
 0.84






### Droping non corelated fearture with dependence var

In [161]:
X_train.drop(not_corelated,axis=1).shape

(20631, 14)

In [162]:
models_fitting(X_train.drop(not_corelated,axis=1),X_test.drop(not_corelated,axis=1),'~low_corr')

LogisticRegression


C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


training accuracy
0.9420289855072463
roc_auc_score 
0.9234417344173442

 f1_score 
 0.7906976744186047

 [[74  8]
 [ 1 17]]

 accuracy_score 
 0.91




Naive Bayes
training accuracy
0.9294265910523
roc_auc_score 
0.8824672170956775

 f1_score 
 0.851851851851852

 [[69  2]
 [ 6 23]]

 accuracy_score 
 0.92




RandomForest
training accuracy
1.0
roc_auc_score 
0.9304743339831059

 f1_score 
 0.8181818181818181

 [[74  7]
 [ 1 18]]

 accuracy_score 
 0.92




Decision Tree
training accuracy
1.0
roc_auc_score 
0.9163713678242381

 f1_score 
 0.7619047619047621

 [[74  9]
 [ 1 16]]

 accuracy_score 
 0.9




KNN
roc_auc_score 
0.8809355067328136

 f1_score 
 0.7142857142857143

 [[73 10]
 [ 2 15]]

 accuracy_score 
 0.88






#### feature selection 
- using SelectFromModel(Lasso(alpha=0.005, random_state=0))

In [163]:
X_train[selected_feat].shape

(20631, 10)

In [164]:
models_fitting(X_train[selected_feat],X_test[selected_feat],'FS_lasso_rs_0')

LogisticRegression


C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


training accuracy
0.9461489990790558
roc_auc_score 
0.9092261904761905

 f1_score 
 0.7317073170731707

 [[74 10]
 [ 1 15]]

 accuracy_score 
 0.89




Naive Bayes
training accuracy
0.9319955406911928
roc_auc_score 
0.9305477131564088

 f1_score 
 0.8749999999999999

 [[73  4]
 [ 2 21]]

 accuracy_score 
 0.94




RandomForest
training accuracy
1.0
roc_auc_score 
0.9234417344173442

 f1_score 
 0.7906976744186047

 [[74  8]
 [ 1 17]]

 accuracy_score 
 0.91




Decision Tree
training accuracy
1.0
roc_auc_score 
0.9144062688366486

 f1_score 
 0.8260869565217391

 [[73  6]
 [ 2 19]]

 accuracy_score 
 0.92




KNN
roc_auc_score 
0.8235294117647058

 f1_score 
 0.6

 [[72 13]
 [ 3 12]]

 accuracy_score 
 0.84






### Scaling and direct

In [165]:
# Scaling
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [166]:
'''df_minmax=pd.DataFrame(X_train_scaled,columns=X_train.columns)
df_minmax.head(200)'''

'df_minmax=pd.DataFrame(X_train_scaled,columns=X_train.columns)\ndf_minmax.head(200)'

In [167]:
X_train_scaled.shape

(20631, 26)

In [168]:
models_fitting(X_train_scaled,X_test_scaled,"Scaled_direct")

LogisticRegression
training accuracy
0.9609325771896661
roc_auc_score 
0.9573170731707318

 f1_score 
 0.8372093023255813

 [[75  7]
 [ 0 18]]

 accuracy_score 
 0.93




Naive Bayes
training accuracy
0.8788231302408996
roc_auc_score 
0.8378378378378378

 f1_score 
 0.8064516129032258

 [[63  0]
 [12 25]]

 accuracy_score 
 0.88




RandomForest
training accuracy
1.0
roc_auc_score 
0.8979857050032489

 f1_score 
 0.7727272727272727

 [[73  8]
 [ 2 17]]

 accuracy_score 
 0.9




Decision Tree
training accuracy
1.0
roc_auc_score 
0.8458498023715415

 f1_score 
 0.7499999999999999

 [[70  7]
 [ 5 18]]

 accuracy_score 
 0.88




KNN
roc_auc_score 
0.9304743339831059

 f1_score 
 0.8181818181818181

 [[74  7]
 [ 1 18]]

 accuracy_score 
 0.92






### Feature extraction 
- 2nd degree polynomialFeatures of [a, b] becomes [1, a, b, a^2, ab, b^2]

In [169]:
from sklearn.preprocessing import PolynomialFeatures
# 2nd degree polynomialFeatures of [a, b] becomes [1, a, b, a^2, ab, b^2]
poly = PolynomialFeatures(2)
X_train_transformed = poly.fit_transform(X_train_scaled)
X_test_transformed = poly.fit_transform(X_test_scaled)

print(X_train_scaled.shape)
print(X_train_transformed.shape)

(20631, 26)
(20631, 378)


In [170]:
logreg.fit(X_train_transformed, y_train)


C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [171]:
from sklearn.feature_selection import SelectFromModel
select_features = SelectFromModel(logreg, threshold='mean', prefit=True)
select_features.get_support()
feature_names = poly.get_feature_names()

print('Original features:\n', X_train.columns)
print('Best features:\n', np.array(feature_names)[select_features.get_support()])
np.array(feature_names)[select_features.get_support()].shape

Original features:
 Index(['vehicleId', 'days', 'ecoMode', 'cityMode', 'sportMode', 's1', 's2',
       's3', 's4', 's5', 's6', 's7', 's8', 's9', 's10', 's11', 's12', 's13',
       's14', 's15', 's16', 's17', 's18', 's19', 's20', 's21'],
      dtype='object')
Best features:
 ['1' 'x1' 'x8' 'x10' 'x11' 'x12' 'x13' 'x15' 'x16' 'x17' 'x18' 'x19' 'x21'
 'x24' 'x25' 'x0^2' 'x0 x1' 'x0 x3' 'x0 x8' 'x0 x12' 'x0 x13' 'x0 x15'
 'x0 x17' 'x0 x18' 'x0 x24' 'x1^2' 'x1 x2' 'x1 x6' 'x1 x7' 'x1 x10'
 'x1 x12' 'x1 x13' 'x1 x17' 'x1 x18' 'x1 x25' 'x2 x3' 'x2 x8' 'x2 x11'
 'x2 x13' 'x2 x16' 'x2 x18' 'x2 x21' 'x3^2' 'x3 x13' 'x3 x15' 'x3 x17'
 'x3 x18' 'x3 x19' 'x6^2' 'x6 x8' 'x6 x12' 'x6 x15' 'x6 x17' 'x6 x19'
 'x6 x25' 'x7 x12' 'x7 x13' 'x7 x15' 'x7 x17' 'x7 x18' 'x8^2' 'x8 x10'
 'x8 x12' 'x8 x13' 'x8 x15' 'x8 x16' 'x8 x17' 'x8 x19' 'x8 x21' 'x10^2'
 'x10 x11' 'x10 x12' 'x10 x13' 'x10 x15' 'x10 x16' 'x10 x17' 'x10 x18'
 'x10 x19' 'x10 x21' 'x10 x24' 'x10 x25' 'x11^2' 'x11 x13' 'x11 x16'
 'x11 x18' 'x11 

(126,)

### Feature extraction+feature selection+scaled
- feature selection SelectFromModel(logreg, threshold='mean', prefit=True)

In [172]:
X_train_transformed[:, select_features.get_support()].shape

(20631, 126)

In [173]:
models_fitting(X_train_transformed[:, select_features.get_support()],X_test_transformed[:, select_features.get_support()],"FE_FS_scaled")

LogisticRegression


C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


training accuracy
0.9637438805680771
roc_auc_score 
0.9304743339831059

 f1_score 
 0.8181818181818181

 [[74  7]
 [ 1 18]]

 accuracy_score 
 0.92




Naive Bayes
training accuracy
0.9165333721099317
roc_auc_score 
0.8928571428571429

 f1_score 
 0.8727272727272728

 [[69  1]
 [ 6 24]]

 accuracy_score 
 0.93




RandomForest
training accuracy
1.0
roc_auc_score 
0.90625

 f1_score 
 0.7999999999999999

 [[73  7]
 [ 2 18]]

 accuracy_score 
 0.91




Decision Tree
training accuracy
1.0
roc_auc_score 
0.8642191142191142

 f1_score 
 0.7659574468085107

 [[71  7]
 [ 4 18]]

 accuracy_score 
 0.89




KNN
roc_auc_score 
0.9144062688366486

 f1_score 
 0.8260869565217391

 [[73  6]
 [ 2 19]]

 accuracy_score 
 0.92






### Feature extraction+feature selection+scaled
- SelectFromModel(Lasso(alpha=0.001, random_state=0))

In [174]:
feature_sel_model = SelectFromModel(Lasso(alpha=0.001, random_state=0)) # remember to set the seed, the random state in this function
feature_sel_model.fit(X_train_transformed,y_train)

SelectFromModel(estimator=Lasso(alpha=0.001, random_state=0))

In [175]:
feature_names = poly.get_feature_names()

print('Original features:\n', X_train.columns)
print('Best features:\n', np.array(feature_names)[feature_sel_model.get_support()])
np.array(feature_names)[feature_sel_model.get_support()].shape

Original features:
 Index(['vehicleId', 'days', 'ecoMode', 'cityMode', 'sportMode', 's1', 's2',
       's3', 's4', 's5', 's6', 's7', 's8', 's9', 's10', 's11', 's12', 's13',
       's14', 's15', 's16', 's17', 's18', 's19', 's20', 's21'],
      dtype='object')
Best features:
 ['x13' 'x18' 'x0 x1' 'x1 x16' 'x6 x15' 'x6 x25' 'x7 x8' 'x7 x15' 'x8^2'
 'x8 x15' 'x8 x16' 'x8 x24' 'x8 x25' 'x11 x15' 'x12 x15' 'x15^2' 'x15 x16'
 'x15 x19' 'x15 x25' 'x16^2' 'x18^2' 'x19 x24' 'x21^2']


(23,)

### applying 2nd degree polynomialFeatures and selecting best feature
- but not up the mark

In [176]:
X_train_transformed[:, feature_sel_model.get_support()].shape

(20631, 23)

In [177]:
models_fitting(X_train_transformed[:, feature_sel_model.get_support()],X_test_transformed[:, feature_sel_model.get_support()],"FE_FS_lasso_rs0_scaled")

LogisticRegression
training accuracy
0.9608356356938588
roc_auc_score 
0.9518072289156627

 f1_score 
 0.8095238095238095

 [[75  8]
 [ 0 17]]

 accuracy_score 
 0.92




Naive Bayes
training accuracy
0.9342736658426639
roc_auc_score 
0.8768191268191268

 f1_score 
 0.8235294117647058

 [[70  4]
 [ 5 21]]

 accuracy_score 
 0.91




RandomForest
training accuracy
1.0
roc_auc_score 
0.9375

 f1_score 
 0.8444444444444444

 [[74  6]
 [ 1 19]]

 accuracy_score 
 0.93




Decision Tree
training accuracy
1.0
roc_auc_score 
0.9224941724941725

 f1_score 
 0.8510638297872342

 [[73  5]
 [ 2 20]]

 accuracy_score 
 0.93




KNN
roc_auc_score 
0.90625

 f1_score 
 0.7999999999999999

 [[73  7]
 [ 2 18]]

 accuracy_score 
 0.91






# result

- _A  -accuracy
- _f1 -f1_score
- _AUC- Area under the curve


- direct                 - applying directly
- ~low_corr              - droping low corelation var with dep var
- FS_lasso_rs_0          - feature selection using lasso with randam state=0
- Scaled_direct          - Scaled and directly applying
- FE_FS_scaled           - feature engg & feature selection & Scaled
- FE_FS_lasso_rs0_scaled - feature engg & feature selection & Scaled using lasso with randam state=0

In [178]:
result_df

Classifier  direct_A  direct_f1  direct_AUC  ~low_corr_A  \
0  LogisticRegression      0.89   0.731707    0.909226         0.91   
1         Naive Bayes      0.93   0.867925    0.896825         0.92   
2        RandomForest      0.91   0.800000    0.906250         0.92   
3       Decision Tree      0.91   0.808511    0.893357         0.90   
4                 KNN      0.84   0.600000    0.823529         0.88   

   ~low_corr_f1  ~low_corr_AUC  FS_lasso_rs_0_A  FS_lasso_rs_0_f1  \
0      0.790698       0.923442             0.89          0.731707   
1      0.851852       0.882467             0.94          0.875000   
2      0.818182       0.930474             0.91          0.790698   
3      0.761905       0.916371             0.92          0.826087   
4      0.714286       0.880936             0.84          0.600000   

   FS_lasso_rs_0_AUC  Scaled_direct_A  Scaled_direct_f1  Scaled_direct_AUC  \
0           0.909226             0.93          0.837209           0.957317   
1           0.930548             0.88          0.806452           0.837838   
2           0.923442             0.90          0.772727           0.897986   
3           0.914406             0.88          0.750000           0.845850   
4           0.823529             0.92          0.818182           0.930474   

   FE_FS_scaled_A  FE_FS_scaled_f1  FE_FS_scaled_AUC  \
0            0.92         0.818182          0.930474   
1            0.93         0.872727          0.892857   
2            0.91         0.800000          0.906250   
3            0.89         0.765957          0.864219   
4            0.92         0.826087          0.914406   

   FE_FS_lasso_rs0_scaled_A  FE_FS_lasso_rs0_scaled_f1  \
0                      0.92                   0.809524   
1                      0.91                   0.823529   
2                      0.93                   0.844444   
3                      0.93                   0.851064   
4                      0.91                   0.800000   

   FE_FS_lasso_rs0_scaled_AUC  
0                    0.951807  
1                    0.876819  
2                    0.937500  
3                    0.922494  
4                    0.906250

In [179]:
# to plot grahp but is done regression model
def gragh(df,s,e):
    fig = plt.figure(figsize=(13,5))
    if e > 100 or e <= 0:
        select_engines = list(pd.unique(df.vehicleId))
    else:
        select_engines = np.random.choice(range(1,101), e, replace=False)
        
    sub1 = fig.add_subplot(221)
    sub1.set_title('time series: ' + s +' / days(cycle)')
    sub1.set_xlabel('days')
    for i in select_engines:
        df1 = df[['days', s]][df.vehicleId == i]
        sub1.plot(df1['days'],df1[s])
    plt.tight_layout()
    plt.show()

In [180]:
sensor_names = ['s{}'.format(i) for i in range(1,22)]
'''for sensor in sensor_names:
    gragh(train,sensor,10)'''

'for sensor in sensor_names:\n    gragh(train,sensor,10)'